### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by jbrnfnd** [pmorrell/SNPMeta#3]
Hello There,

I want to use this tool, but unfortunately its not working correctly.
When I try to reproduce your example, following happens
$ /opt/Bio/SNPMeta/20160930/bin/SNPMeta.py -f Example_SNPs.fasta -l 60 -a XXX@YY.de -o converted_seq_info_100_9.output -q 'Drosophila simulans' -t 'Drosophila simulans' --outfmt tabular
Annotating RIL01_12001_2
    Contextual sequence length: 60
    Running BLAST with the following parameters: ...
        Program:  blastn
        E-value:  5e-10
        Max hits: 5
    Done!
    Fetching GenBank records ...
        Requesting batch 1 of 1 (2 records total)
    Done!
    Extracting annotation information from GenBank records
    Aligning GenBank record and query sequence ... Done!
/opt/Bio/python/3.4.5/lib/python3.4/site-packages/Bio/Seq.py:2071: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
Annotating RIL01_12001_3
    Contextual sequence length: 60
    Running BLAST with the following parameters: ...
        Program:  blastn
        E-value:  5e-10
        Max hits: 5
    Done!
    Fetching GenBank records ... Traceback (most recent call last):
  File "/opt/Bio/SNPMeta/20160930/bin/SNPMeta.py", line 171, in <module>
    main()
  File "/opt/Bio/SNPMeta/20160930/bin/SNPMeta.py", line 112, in main
    gb_success = genbank.fetch_gb_records()
  File "/data/Bio/SNPMeta/20160930/bin/snpmeta/SNPAnnotation/genbank.py", line 105, in fetch_gb_records
    starts.append(str(hitstart))
UnboundLocalError: local variable 'hitstart' referenced before assignment

---

I am using python 3.4.5 (compiled and installed in /opt/Bio/python/3.4.5) with biopython installed via pip

Some Suggestions?
Do you need more infos?

Greetings

**Comment by TomJKono** [comment]
Hello,

This is an issue with an outdated version of SNPMeta. It has been fixed in the version that is available here: https://github.com/MorrellLAB/SNPMeta.

I apologize for the confusion with the two branches of the program.

**Comment by jbrnfnd** [comment]
Hello,

thanks for that info.
This version works.
Maybe For future users you should change the link on your homepage, so they will find the correct version.

Greetings
Jens
